import React from 'react'
import CreateEvent from '../../../../components/createEvent/CreateEvent'
import AppNavbar from '../../../../components/AppNavbar'
import Head from 'next/head'

const index = () => {
    return (
        <div className='w-screen h-screen' >
            <Head>
                <title>Turpio | Creating Event For Soccer Booking</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <AppNavbar
                pageTitle="Soccer-Field-Booking"
                disableSecondControl={true}
                backBtn={true}
            />
            <CreateEvent nextLink="soccer-field-booking/availability" />
        </div>
    )
}

export default index

// export const getServerSideProps = async function ({req, res}) {
//   if (!req.user) {
//       return {
//           redirect: {
//               destination: '/',
//               permanent: true,
//           },
//       }
//   }

//   return {
//       props: req.user ,
//   }
// }