import React, { useState } from 'react'
import Head from 'next/head';
import AppNavbar from '../../components/AppNavbar'
import useStateContext from '../../context/ContextProvider';
import EditCreateEvent from '../../components/createEvent/EditCreateEvent';
import EditAvailability from '../../components/availability/EditAvailability';
import EditPayment from '../../components/payment/EditPayment';


const id = () => {
    const { editEvent, handelEditEventTab } = useStateContext();
    return (
        <div className='w-screen h-screen' >
            <Head>
                <title>{`Working Hours - Edit ${"One-on-One Event Type"} - Turpio`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <AppNavbar
                pageTitle={`Edit ${"One-on-One Event Type"}`}
                disableSecondControl={true}
                backBtn={true}
                backBtnNavigate="/home"
            />
            <div className='w-screen min-h-screen py-32 flex items-center flex-col gap-4' >
                <EditCreateEvent
                    setEditEvent={() => handelEditEventTab("create")}
                    editEvent={editEvent.create}
                />
                <EditAvailability
                    setEditEvent={() => handelEditEventTab("availability")}
                    editEvent={editEvent.availability}
                />
                <EditPayment
                    setEditEvent={() => handelEditEventTab("payment")}
                    editEvent={editEvent.payment}
                />
            </div>


        </div>
    )
}

export default id